"""Score structured Medical-NLA v2 readouts.

This scorer expects rows generated by `src.run_nla` with `nla_output` containing
the inner `<readout>...</readout>` XML. It measures:

- readout parse rate
- answer tag parse rate
- diagnosis hit by matching the `<answer>` text to gold aliases
- supporting cue recall by matching gold cue strings in `<supporting_cues>`
"""

from __future__ import annotations

import argparse
import html
import re
import sys
from collections import Counter, defaultdict
from pathlib import Path
from statistics import mean
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from scripts.score_specificity_outputs import contains_term
from src.jsonl import read_jsonl, write_jsonl


TAG_RE_TEMPLATE = r"<{tag}>\s*(.*?)\s*</{tag}>"


def clean_text(text: Any) -> str:
    return " ".join(html.unescape(str(text or "")).split())


def extract_tag(text: str, tag: str) -> tuple[str, bool]:
    match = re.search(TAG_RE_TEMPLATE.format(tag=re.escape(tag)), text, flags=re.DOTALL | re.IGNORECASE)
    if match is None:
        return "", False
    return clean_text(match.group(1)), True


def diagnosis_aliases(row: dict[str, Any]) -> list[str]:
    aliases = [clean_text(value) for value in row.get("diagnosis_aliases") or [] if clean_text(value)]
    name = clean_text(row.get("diagnosis_name") or row.get("gold_diagnosis_name"))
    if name:
        aliases.insert(0, name)
    diagnosis_id = clean_text(row.get("diagnosis_id") or row.get("gold_diagnosis_id"))
    if diagnosis_id:
        aliases.append(diagnosis_id.replace("_", " "))
    deduped = []
    for alias in aliases:
        if alias and alias.lower() not in {item.lower() for item in deduped}:
            deduped.append(alias)
    return deduped


def cue_targets(row: dict[str, Any]) -> list[str]:
    cues = row.get("cue_targets") or []
    if isinstance(cues, str):
        cues = [cues]
    deduped = []
    for cue in cues:
        text = clean_text(cue)
        if text and text.lower() not in {item.lower() for item in deduped}:
            deduped.append(text)
    return deduped


def hit_terms(text: str, terms: list[str]) -> list[str]:
    return [term for term in terms if contains_term(text, term)]


def score_row(row: dict[str, Any]) -> dict[str, Any]:
    output = clean_text(row.get("nla_output") or row.get("raw_nla_output"))
    readout_text, parsed_readout = extract_tag(output, "readout")
    parse_source = readout_text if parsed_readout else output
    task_type, parsed_task_type = extract_tag(parse_source, "task_type")
    answer, parsed_answer = extract_tag(parse_source, "answer")
    supporting_cues, parsed_supporting_cues = extract_tag(parse_source, "supporting_cues")

    aliases = diagnosis_aliases(row)
    answer_hits = hit_terms(answer, aliases) if answer else []
    output_answer_hits = hit_terms(output, aliases)
    cues = cue_targets(row)
    cue_hits = hit_terms(supporting_cues, cues) if supporting_cues else []
    cue_recall = len(cue_hits) / len(cues) if cues else None
    return {
        **row,
        "readout_text": readout_text,
        "parsed_readout": parsed_readout,
        "parsed_task_type": parsed_task_type,
        "parsed_answer": parsed_answer,
        "parsed_supporting_cues": parsed_supporting_cues,
        "task_type_readout": task_type,
        "answer_readout": answer,
        "supporting_cues_readout": supporting_cues,
        "diagnosis_aliases_scored": aliases,
        "answer_hits": answer_hits,
        "output_answer_hits": output_answer_hits,
        "answer_hit": bool(answer_hits),
        "output_answer_hit": bool(output_answer_hits),
        "gold_cue_targets": cues,
        "cue_hits": cue_hits,
        "cue_hit_count": len(cue_hits),
        "cue_count": len(cues),
        "cue_recall": cue_recall,
    }


def write_summary(path: Path, rows: list[dict[str, Any]]) -> None:
    by_gold: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for row in rows:
        by_gold[str(row.get("diagnosis_id") or row.get("gold_diagnosis_id"))].append(row)

    n = len(rows)
    parsed_readout = sum(bool(row["parsed_readout"]) for row in rows)
    parsed_answer = sum(bool(row["parsed_answer"]) for row in rows)
    parsed_cues = sum(bool(row["parsed_supporting_cues"]) for row in rows)
    answer_hits = sum(bool(row["answer_hit"]) for row in rows)
    output_answer_hits = sum(bool(row["output_answer_hit"]) for row in rows)
    cue_recalls = [float(row["cue_recall"]) for row in rows if row["cue_recall"] is not None]
    selected_answers = Counter(row["answer_readout"] or "-" for row in rows)

    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        f.write("# Medical-NLA v2 Readout Summary\n\n")
        f.write("Structured readout scoring; lexical alias/cue screening only.\n\n")
        f.write(f"- n: {n}\n")
        f.write(f"- parsed_readout: {parsed_readout}/{n}\n")
        f.write(f"- parsed_answer: {parsed_answer}/{n}\n")
        f.write(f"- parsed_supporting_cues: {parsed_cues}/{n}\n")
        f.write(f"- answer_hit: {answer_hits}/{n}\n")
        f.write(f"- answer_hit_rate: {answer_hits / n if n else 0:.4f}\n")
        f.write(f"- output_answer_hit: {output_answer_hits}/{n}\n")
        f.write(f"- output_answer_hit_rate: {output_answer_hits / n if n else 0:.4f}\n")
        f.write(f"- mean_cue_recall: {mean(cue_recalls) if cue_recalls else 0:.4f}\n\n")

        f.write("## By Gold Diagnosis\n\n")
        f.write("| diagnosis_id | n | answer_hit_rate | answer_hits | mean_cue_recall |\n")
        f.write("|---|---:|---:|---:|---:|\n")
        rates = []
        for diagnosis_id, items in by_gold.items():
            hits = sum(bool(row["answer_hit"]) for row in items)
            recalls = [float(row["cue_recall"]) for row in items if row["cue_recall"] is not None]
            rates.append((hits / len(items), diagnosis_id, len(items), hits, mean(recalls) if recalls else 0.0))
        for rate, diagnosis_id, count, hits, recall in sorted(rates):
            f.write(f"| {diagnosis_id} | {count} | {rate:.4f} | {hits} | {recall:.4f} |\n")

        f.write("\n## Top Answer Readouts\n\n")
        f.write("| answer | count |\n")
        f.write("|---|---:|\n")
        for answer, count in selected_answers.most_common(25):
            display = answer.replace("\n", " ")
            if len(display) > 120:
                display = display[:117] + "..."
            f.write(f"| {display} | {count} |\n")

        f.write("\n## Examples\n\n")
        f.write("| id | expected | answer | hit | cue_recall | supporting_cues |\n")
        f.write("|---|---|---|---:|---:|---|\n")
        for row in rows[:100]:
            answer = (row["answer_readout"] or "-").replace("\n", " ")
            cues = (row["supporting_cues_readout"] or "-").replace("\n", " ")
            if len(cues) > 160:
                cues = cues[:157] + "..."
            f.write(
                f"| {row['id']} | {row.get('diagnosis_name') or row.get('gold_diagnosis_name')} | "
                f"{answer} | {'Y' if row['answer_hit'] else 'N'} | "
                f"{row['cue_recall'] if row['cue_recall'] is not None else '-'} | {cues} |\n"
            )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", required=True)
    parser.add_argument("--output-jsonl", required=True)
    parser.add_argument("--summary-md", required=True)
    args = parser.parse_args()

    scored = [score_row(row) for row in read_jsonl(args.input)]
    if not scored:
        raise ValueError("No rows to score.")
    write_jsonl(Path(args.output_jsonl), scored)
    write_summary(Path(args.summary_md), scored)
    print(f"[done] wrote {len(scored)} scored rows to {args.output_jsonl}")
    print(f"[done] wrote summary to {args.summary_md}")


if __name__ == "__main__":
    main()
